spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5959@Ssol
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true


jwt:
  header: Authorization
  secret: dG95cHJvamVjdC1iaXQ1MDItdGVhbS13ZS1jYW4tbWFkZS1pdC1mb3ItdGhlLWJlc3Qtb2YtbXktbGlmZS1kb250LWJlLWFmZnJhaWQtb2YtQWxsLW9mLUVycm9y
  token-validity-in-seconds: 86400

